---
displayMode: compact
---
gantt
dateFormat YYYY-MM-DD
title Character Design Process

section PC, Concept Making
Gavin, Cordelia, Chunkz               :done, 2025-03-12,2025-03-13
Chunkz, continued                     :done, 2025-03-20, 1d

section PC, Sketches and Changes
Gavin                                 :done, 2025-03-12,2025-03-13
Siren Witch                           :done, 2025-03-12,2025-03-13
Siren Witch to Cordelia               :done, 2025-03-24, 1d
Chunkz                                :done, 2025-03-20, 1d

section PC, Animation
Gavin, Cordelia, Chunkz (Foundation + Colored) :done, 2025-03-25,2025-03-27

section PC, Final Line-up
Gavin, Cordelia, Chunkz (Idle Pixel) :milestone, 2025-03-22,2025-03-23

section NPC, Interactive NPC
Sheriff                              :done, 2025-03-17, 1d

section NPC, Enemies

section Environment

%% Thank you for viewing!
